### ISSUE TITLE
Type of this value must be known in this context on 1.25.0-nightly

### ISSUE THREAD

**Issue by snowe2010** [AndyBarron/app-dirs-rs#28]
```
❯ rustc -V
rustc 1.25.0-nightly (79a521bb9 2018-01-15)
```

I receive the error 

```
error[E0619]: the type of this value must be known in this context
  --> /Users/tylerthrailkill/.cargo/registry/src/github.com-1ecc6299db9ec823/app_dirs-1.1.1/src/imp/platform/macos.rs:10:40
   |
10 |         Ok(Component::RootDir.as_ref().into())
   |                                        ^^^^

error: aborting due to previous error

error: Could not compile `app_dirs`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

when attempting to compile my application using app_dirs with 1.25.0-nightly

**Comment by netgusto** [comment]
Same for me.

**Comment by skade** [comment]
This seems to be a backwards compatibility bug.

I _think_ it's this one.

https://github.com/rust-lang/rust/issues/47709

**Comment by theotherjimmy** [comment]
Travis log from my application: https://travis-ci.org/ARMmbed/cmsis-pack-manager/jobs/335350045

**Comment by daboross** [comment]
Happens on Mac OS on travis for me: https://travis-ci.org/daboross/screeps-rs/jobs/339353849#L337

**Comment by DataAnalysisCosby** [comment]
I experience this bug as well

**Comment by pakoito** [comment]
The bug remains in 1.26.0-nightly :(

**Comment by skade** [comment]
Hi, this will break on stable tomorrow, with the release of Rust 1.25. @AndyBarron, can you do a release or at least give someone release rights? I'd also be happy to do that, in this case, add @skade to this repository and skade (florian.gilcher@asquera.de) at crates.io.

**Comment by icefoxen** [comment]
I've made a fork of this project with the fix included: https://github.com/app-dirs-rs/app_dirs2

@skade If you are willing to help maintain it I will gladly give you github and crates.io access.

**Comment by JustAPerson** [comment]
Sent the maintainer an email asking to either check github or relinquish control of the crate.

**Comment by pakoito** [comment]
@icefoxen meanwhile, how can I build `ggez` locally?

**Comment by JustAPerson** [comment]
@pakoito [this appears the correct way to handle this in cargo](https://doc.rust-lang.org/cargo/reference/manifest.html#the-patch-section)

**Comment by icefoxen** [comment]
@pakoito The devel branch uses `app_dirs2`, I hope to publish it tonight.
